name: Deploy Web App to Azure

on:
  push:
    branches: [ main, development ]
    paths: 
      - 'apps/web/**'
      - 'backend/**'
      - '.github/workflows/deploy-web.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          apps/web/package-lock.json
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install root dependencies
      run: npm install
    
    - name: Install web dependencies
      run: cd apps/web && npm install
    
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint web app
      run: cd apps/web && npm run lint
    
    - name: Type check web app
      run: cd apps/web && npm run type-check
    
    - name: Test Django backend
      run: |
        cd backend
        python manage.py test
    
    - name: Build web app
      run: cd apps/web && npm run build

  deploy-backend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Collect static files
      run: |
        cd backend
        python manage.py collectstatic --noinput
    
    # Deploy to Azure App Service (Backend)
    - name: Deploy Django to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_BACKEND_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        package: ./backend

  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: apps/web/package-lock.json
    
    - name: Install dependencies
      run: cd apps/web && npm install
    
    - name: Build Next.js app
      run: cd apps/web && npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
    
    # Deploy to Azure Static Web Apps (Frontend)
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/apps/web"
        output_location: "out"
        skip_app_build: true